import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
    template: '%s | personal-site',
    default: 'personal-site',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex w-full justify-center align-middle">Header</header>
        {children}
        <footer className="flex w-full justify-center align-middle">Footer</footer>
      </body>
    </html>
  );
}
