import { Inter } from "next/font/google";
import Aside from "../components/dashboard/aside";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={
        inter.className + " flex items-center h-screen justify-center w-full"
      }
    >
      <Aside />
      <main className="h-[98vh] w-[79%] flex rounded-3xl bg-slate-200 flex-col items-center">
        {children}
      </main>
    </div>
  );
}
