import { Inter } from "next/font/google";
import Aside from "../components/dashboard/aside";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className={inter.className}>
      <Aside />
      {children}
    </body>
  );
}
